service: serverless-js-app

frameworkVersion: '4'

provider:
  name: aws
  region: ap-northeast-2
  stage: dev
  architecture: arm64
  ecr:
    images:
      playwright-image:
        path: ./
        file: Dockerfile.chrominum
        platform: linux/arm64

functions:
  runTest:
    image: playwright-image
    events:
      - httpApi:
          path: /
          method: get
    timeout: 30
    memorySize: 3008
    environment:
      HOME: /tmp
      XDG_CONFIG_HOME: /tmp
      XDG_CACHE_HOME: /tmp
      XDG_DATA_HOME: /tmp
      XDG_STATE_HOME: /tmp
      PLAYWRIGHT_BROWSERS_PATH: /tmp

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000