service: serverless-js-app

frameworkVersion: '4'

provider:
  name: aws
  region: ap-northeast-2
  stage: dev
  ecr:
    images:
      playwright-image:
        path: ./

functions:
  hello:
    image: playwright-image
    events:
      - httpApi:
          path: /
          method: get
    timeout: 60
    memorySize: 1024
  runOffercentTest:
    image: playwright-image
    events:
      - httpApi:
          path: /test
          method: get
    timeout: 60
    memorySize: 1024

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000