service: serverless-js-app

frameworkVersion: '4'

provider:
  name: aws
  region: ap-northeast-2
  stage: dev
  architecture: x86_64
  ecr:
    images:
      playwright-image:
        path: ./
        file: Dockerfile.chromium
        platform: linux/amd64

functions:
  runTest:
    image: playwright-image
    events:
      - httpApi:
          path: /
          method: get
    timeout: 900
    memorySize: 3008
    environment:
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
  runOffercentTest:
    image: playwright-image
    events:
      - httpApi:
          path: /test
          method: get
    timeout: 900
    memorySize: 3008
    environment:
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000